name: Build OpenWRT Ninux X86
on:
  workflow_dispatch

jobs:
  build:
    # runs-on: ubuntu-22.04
    runs-on: runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt -y install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget

    - name: Compile X86_64
      run: |
        ./build.sh X86_64

    - name: Upload firmware X86_64 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: X86_64-squashfs
        path: openwrt/bin/targets/x86/64/openwrt-x86-64-generic-ext4-combined-efi.img.gz
