name: Build NNXX
on:
  workflow_dispatch:
    tags:
      - 'v*.*.*'
jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
  x86:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: Initialization environment
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

# GL-Inet GL-MT300n-v2
      - name: Compile glinet_gl-mt300n-v2
        run: |
          ./build.sh glinet_gl-mt300n-v2

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "openwrt/bin/targets/ramips/mt76x8/openwrt-ramips-mt76x8-glinet_gl-mt300n-v2-squashfs-sysupgrade.bin"
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: ${{ env.RELEASE_VERSION }}

