name: PIPPO
on:
  workflow_dispatch:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}


      - name: Crea Dir
        run: mkdir -p ciccio

      - name: Crea un file
        run: touch ciccio/pippo.txt

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ciccio/pippo.txt"
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: ${{ env.RELEASE_VERSION }}


