name: Build OpenWRT Ninux

on:
  workflow_dispatch

env:
  TARGET: X86_64

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt -y install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget

    - name: Compile
      run: |
        ./build.sh $TARGET

    - name: Upload firmware to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.TARGET }}-squashfs
        path: bin/targets/*/*/*squashfs*
        
