name: Build OpenWRT Ninux

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo apt update
        sudo apt -y install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget

    - name: Compile X86_64
      run: |
        ./build.sh X86_64

    - name: Upload firmware X86_64 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: X86_64-squashfs
        path: bin/targets/*/*/*squashfs*.img.gz
        
    - name: Compile glinet_gl-mt300n-v2
      run: |
        ./build.sh glinet_gl-mt300n-v2

    - name: Upload firmware glinet_gl-mt300n-v2 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: glinet_gl-mt300n-v2-squashfs
        path: bin/targets/*/*/*squashfs*

    - name: Compile Lamobo_R1
      run: |
        ./build.sh lamobo_R1

    - name: Upload firmware lamobo_R1 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: lamobo_R1-squashfs
        path: bin/targets/*/*/*squashfs*

    - name: Compile linksys_wrt3200acm
      run: |
        ./build.sh linksys_wrt3200acm

    - name: Upload firmware linksys_wrt3200acm to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: linksys_wrt3200acm-squashfs
        path: bin/targets/*/*/*squashfs*

    - name: Compile Raspberry 3
      run: |
        ./build.sh raspi_3

    - name: Upload firmware raspi_3 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: raspi_3-squashfs
        path: bin/targets/*/*/*squashfs*

    - name: Compile Raspberry 4
      run: |
        ./build.sh raspi_4

    - name: Upload firmware raspi_4 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: raspi_4-squashfs
        path: bin/targets/*/*/*squashfs*

    - name: Compile Totolink X5000R
      run: |
        ./build.sh totolink_X5000R

    - name: Upload firmware totolink_X5000R to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: totolink_X5000R-squashfs
        path: bin/targets/*/*/*squashfs*

    - name: Compile TP-Link C2600
      run: |
        ./build.sh tplink_c2600

    - name: Upload firmware tplink_c2600 to workflow directory
      uses: actions/upload-artifact@main
      with:
        name: tplink_c2600-squashfs
        path: bin/targets/*/*/*squashfs*
